Update pkg lists.
Former-commit-id: 367ed7a9ef54cca32e75d42c60a97d8b79e692f9 [formerly 0043aab337a1401804e09e8f1521c8cfbd924f21]
Former-commit-id: b73563d72c93b0b3a48edbfd47233ced4b9eb825

diff --git a/ubuntu-post-install/functions/configure b/ubuntu-post-install/functions/configure
--- a/ubuntu-post-install/functions/configure
+++ b/ubuntu-post-install/functions/configure
@@ -1,79 +1,84 @@
 #!/bin/bash
 
-dir="$(dirname "$0")"
-
-GSETTINGS="$dir/data/gsettings.list"
 
 # Automatically set preferred gsettings keys as outlined in the 'gsettings.list' file
 # 'gsettings' can be obtained by executing "dconf watch /" and then manually changing settings
-function preferences {
-    show_info 'Setting preferred application-specific & desktop settings...'
-    while IFS= read line
-    do
-        eval gsettings set $line
-    done < "$GSETTINGS"
-    # Done
-    show_success 'Done.'
-    whiptail --title "Finished" --msgbox "Settings changed successfully." 8 78
-    configure
+function set_preferences {
+	# Check list
+	GSETTINGS=$(dirname "$0")'/data/gsettings.list'
+	display_info 'Setting preferred application-specific & desktop settings...'
+	while IFS= read line
+	do
+		eval 'gsettings set' $line
+	done < "$GSETTINGS"
+	# Done
+	display_success 'Settings changed successfully.'
+	whiptail --title "Finished" --msgbox "Settings changed successfully." 8 64
+	configure
+}
+
+# Set preferred bash aliased by copying the 'aliases.list' file to ~/.bash_aliases
+function set_bash_aliases {
+	# Check list
+	ALIASES=$(dirname "$0")'/data/aliases.list'
+	# Draw window
+	if (eval `resize` && whiptail \
+		--title "Preferred Bash Aliases" \
+		--yesno "Current list of preferred bash aliases: \n\n$(while read LINE; do echo "  "$LINE; done < $ALIASES) \n\nProceed?" \
+		$LINES $COLUMNS $(( $LINES - 12 )) \
+		--scrolltext) then
+		display_info 'Setting bash aliases...'
+		# simply copy the list file to the aliases file
+		cp $ALIASES ~/.bash_aliases
+		display_success 'Bash aliases set successfully.'
+		whiptail --title "Finished" --msgbox "Bash aliases set successfully." 8 64
+		configure
+	else
+		configure
+	fi
 }
 
 # Show start-up all start-up applications by modifying the 'NoDisplay' line of their .desktop files
-function startup {
-    show_info 'Changing display of startup applications...'
-    show_warning 'Requires root privileges'
-    sudo sed -i "s/NoDisplay=true/NoDisplay=false/g" /etc/xdg/autostart/*.desktop
-    # Done
-    show_success 'Done.'
-    whiptail --title "Finished" --msgbox "Settings changed successfully." 8 78
-    configure
-}
-
-# Replaces main 'sources.list' with a leaned down version
-function sources {
-    show_info 'Changing system-wide sources.list...'
-    show_warning 'Requires root privileges'
-    sudo cp -r $dir/data/sources.list /etc/apt
-    # Update repository information
-    show_info 'Updating repository information...'
-    show_warning 'Requires root privileges'
-    sudo apt-get update
-    # Done
-    show_success 'Done.'
-    whiptail --title "Finished" --msgbox "Sources list changed successfully." 8 78
-    configure
+function display_startup_apps {
+	display_info 'Changing display of startup applications...'
+	# Admin privileges
+	elevate_privilege "sed -i 's/NoDisplay=true/NoDisplay=false/g' /etc/xdg/autostart/*.desktop"
+	# Done
+	display_success 'Settings changed successfully.'
+	whiptail --title "Finished" --msgbox "Settings changed successfully." 8 64
+	configure
 }
 
 # Disable Apport
-function apport {
-    show_info 'Disabling apport crash dialogs...'
-    show_warning 'Requires root privileges'
-    sudo sed -i "s/enabled=1/enabled=0/g" /etc/default/apport
-    # Done
-    show_success 'Done.'
-    whiptail --title "Finished" --msgbox "Settings changed successfully." 8 78
-    configure
+function disable_apport {
+	display_info 'Disabling apport crash dialogs...'
+	# Admin privileges
+	elevate_privilege "sed -i 's/enabled=1/enabled=0/g' /etc/default/apport"
+	# Done
+	display_success 'Settings changed successfully.'
+	whiptail --title "Finished" --msgbox "Settings changed successfully." 8 64
+	configure
 }
 
 # Configure System
 function configure {
-    eval `resize`
-    CONF=$(whiptail \
-        --notags \
-        --title "Configure System" \
-        --menu "\nWhat would you like to do?" \
-        --cancel-button "Go Back" \
-        $LINES $COLUMNS $(( $LINES - 12 )) \
-        preferences 'Set preferred application-specific & desktop settings' \
-        startup     'Show all startup applications' \
-        sources     'Enable all software sources (replaces sources.list)' \
-        apport      'Disable system crash dialogs' \
-        3>&1 1>&2 2>&3)
-     
-    exitstatus=$?
-    if [ $exitstatus = 0 ]; then
-        $CONF
-    else
-        main
-    fi
+	display_title "Starting 'configure' function..."
+	# check exit status
+	EXITSTATUS=$?
+	if [ $EXITSTATUS = 0 ]; then
+		# Draw window
+		$(eval `resize` && whiptail \
+		--notags \
+		--title "Configure System" \
+		--menu "\nWhat would you like to do?" \
+		--cancel-button "Go Back" \
+		$LINES $COLUMNS $(( $LINES - 12 )) \
+		set_preferences			'Set preferred application-specific & desktop settings' \
+		set_bash_aliases		'Set preferred bash aliases' \
+		display_startup_apps	'Show all startup applications' \
+		disable_apport			'Disable system crash dialogs' \
+		3>&1 1>&2 2>&3)
+	else
+		main
+	fi
 }
diff --git a/ubuntu-post-install/functions/thirdparty b/ubuntu-post-install/functions/thirdparty
--- a/ubuntu-post-install/functions/thirdparty
+++ b/ubuntu-post-install/functions/thirdparty
@@ -1,52 +1,61 @@
 #!/bin/bash
+#
+# When adding (or removing) any functions remember to update the
+# source list and function below to reflect any changes you make
 
-dir="$(dirname "$0")"
+dir=$(dirname "$0")
 
-source $dir/functions/third-party/dropbox
-source $dir/functions/third-party/fontforge
-source $dir/functions/third-party/google-chrome
-source $dir/functions/third-party/inkscape
-source $dir/functions/third-party/keybase
-source $dir/functions/third-party/minecraft
-source $dir/functions/third-party/oracle-java
-source $dir/functions/third-party/rvm
-source $dir/functions/third-party/slack
-source $dir/functions/third-party/synergy
-source $dir/functions/third-party/spotify
-source $dir/functions/third-party/steam
-source $dir/functions/third-party/sublime-text
-source $dir/functions/third-party/vlc
+# Import apps functions; commented-out imports are omitted from the function below.
+
+# source $dir/functions/apps/atom
+source $dir/functions/apps/dropbox
+source $dir/functions/apps/chrome
+source $dir/functions/apps/flatpak
+# source $dir/functions/apps/fontforge
+source $dir/functions/apps/inkscape
+# source $dir/functions/apps/mattermost
+# source $dir/functions/apps/minecraft
+# source $dir/functions/apps/oracle-java
+source $dir/functions/apps/peek
+source $dir/functions/apps/pia
+source $dir/functions/apps/plex
+source $dir/functions/apps/riot
+source $dir/functions/apps/rvm
+source $dir/functions/apps/slack
+# source $dir/functions/apps/spotify
+source $dir/functions/apps/steam
+source $dir/functions/apps/sublime
+# source $dir/functions/apps/synergy
+# source $dir/functions/apps/vlc
 
 # Install Third-Party Applications
 function thirdparty {
-    eval `resize`
-    THIRDPARTY=$(whiptail \
-        --notags \
-        --title "Third-Party Installation" \
-        --menu "\nWhat third-party software would you like to install?" \
-        --ok-button "Install" \
-        --cancel-button "Go Back" \
-        $LINES $COLUMNS $(( $LINES - 12 )) \
-        'dropbox'           'Dropbox' \
-        'fontforge'         'FontForge' \
-        'google-chrome'     'Google Chrome' \
-        'inkscape'          'Inkscape' \
-        'keybase'           'Keybase' \
-        'minecraft'         'Minecraft' \
-        'oracle-java'       'Oracle Java' \
-        'rvm'               'Ruby Version Manager (RVM)' \
-        'slack'             'Slack' \
-        'spotify'           'Spotify' \
-        'steam'             'Steam' \
-        'synergy'           'Synergy' \
-        'sublime-text'      'Sublime Text 3' \
-        'vlc'               'VLC Player' \
-        3>&1 1>&2 2>&3)
-     
-    exitstatus=$?
-    if [ $exitstatus = 0 ]; then
-        $THIRDPARTY
-    else
-        main
-    fi
+	display_title "Starting 'thirdparty' function..."
+	# check exit status
+	EXITSTATUS=$?
+	if [ $EXITSTATUS = 0 ]; then
+		# Draw window
+		$(eval `resize` && whiptail \
+		--notags \
+		--title "Third-Party Applications" \
+		--menu "\nWhich third-party app would you like to install?" \
+		--ok-button "Install" \
+		--cancel-button "Go Back" \
+		$LINES $COLUMNS $(( $LINES - 12 )) \
+		'dropbox'		'Dropbox' \
+		'flatpak'		'Flatpak' \
+		'chrome'		'Google Chrome' \
+		'inkscape'		'Inkscape' \
+		'peek'			'Peek' \
+		'pia'			'Private Internet Access' \
+		'plex'			'Plex Media Server' \
+		'riot'			'Riot Chat' \
+		'rvm'			'Ruby Version Manager (RVM)' \
+		'slack'			'Slack Desktop' \
+		'steam'			'Steam' \
+		'sublime'		'Sublime Text 3' \
+		3>&1 1>&2 2>&3)
+	else
+		main
+	fi
 }
