Update pkg lists.

diff --git a/ubuntu-post-install/functions/gnome b/ubuntu-post-install/functions/gnome
--- a/ubuntu-post-install/functions/gnome
+++ b/ubuntu-post-install/functions/gnome
@@ -1,91 +1,122 @@
 #!/bin/bash
 
-dir="$(dirname "$0")"
-
-GNOMEAPPS="$dir/data/gnome-apps.list"
-
-# Cleanup System
-function gnome {
-    eval `resize` 
-    GNOME=$(whiptail \
-        --notags \
-        --title "Install Latest GNOME" \
-        --menu "\nWhat would you like to do?" \
-        --cancel-button "Go Back" \
-        $LINES $COLUMNS $(( $LINES - 12 )) \
-        gnome-upgrade   'Update to latest GNOME' \
-        gnome-desktop   'Install basic GNOME desktop' \
-        gnome-apps      'Install GNOME core applications' \
-        3>&1 1>&2 2>&3)
-     
-    exitstatus=$?
-    if [ $exitstatus = 0 ]; then
-        $GNOME
-    else
-        main
-    fi
-}
-
 # Add GNOME PPA
-function gnome-upgrade {
-    # Add repository
-    show_info 'Adding GNOME3 PPA to software sources...'
-    show_warning 'Requires root privileges'
-    sudo add-apt-repository -y ppa:gnome3-team/gnome3
-    # Update repository information
-    show_info 'Updating repository information...'
-    sudo apt-get update -y
-    show_success 'Done.'
-    # Upgrade GNOME
-    show_info 'Updating repository information...'
-    sudo apt-get dist-upgrade -y
-    show_success 'Done.'
-    gnome
+function upgrade_gnome {
+	PPA=ppa:gnome3-team/gnome3
+	display_title "Starting 'upgrade_gnome' function..."
+	# Add repository
+	display_info 'Adding GNOME3 PPA to software sources...'
+	# Admin privileges
+	elevate_privilege "add-apt-repository -y $PPA"
+	# Update repository information
+	display_info 'Updating repository information...'
+	# Admin privileges
+	elevate_privilege "apt update -y"
+	display_success 'Done.'
+	# Upgrade GNOME
+	display_info 'Upgrading GNOME software...'
+	# Admin privileges
+	elevate_privilege "apt dist-upgrade -y"
+	display_success "Upgrade complete."
+	gnome
 }
 
 # Install GNOME Desktop
-function gnome-desktop {
-	# Install
-    echo 'Installing GNOME Desktop...'
-    show_warning 'Requires root privileges'
-    sudo apt-get install -y fonts-cantarell gnome-shell gnome-shell-extensions gnome-session gnome-terminal nautilus
-    # Done
-    show_success 'Done.'
-    # Check
-    EXITSTATUS=$1
-    if [[ $EXITSTATUS != 0 ]]; then
-        whiptail --title "Finished" --msgbox "GNOME desktop is installed." 8 78
-        gnome
-    else
-        whiptail --title "Finished" --msgbox "GNOME desktop installation complete." 8 78
-        gnome
-    fi
-    gnome
+function install_gnome_desktop {
+	display_title "Starting 'install_gnome_desktop' function..."
+	# Check list
+	GNOMEDESKTOP=$(dirname "$0")'/data/gnome-desktop.list'
+	# Draw window
+	if (eval `resize` && whiptail \
+		--title "GNOME Desktop" \
+		--yesno "Packages to install for a basic GNOME desktop: \n\n$(for LINE in $(cat $GNOMEDESKTOP); do echo '  '$LINE; done) \n\nProceed with installation?" \
+		$LINES $COLUMNS $(( $LINES - 12 )) \
+		--scrolltext) then
+		# Install loop
+		display_info 'Installing GNOME desktop...'
+		for PACKAGE in $(cat $GNOMEDESKTOP); do
+			# Check if package is installed
+			check_packages $PACKAGE
+			EXITSTATUS=$?
+			# If package is not installed
+			if [ $EXITSTATUS = 1 ]; then
+				# Install package
+				display_info "'$PACKAGE' is not installed. Installing..."
+				# Admin privileges
+				elevate_privilege "apt install -y --no-install-recommends $PACKAGE"
+				# Done
+				display_success "'$PACKAGE' installation is complete."
+			else
+				# Show already installed message
+				echo "Package '$PACKAGE' is installed."
+			fi
+		done
+		# Finish
+		display_success "Installation complete."
+		whiptail --title "Finished" --msgbox "Installation complete." 8 64
+		gnome
+	else
+		gnome
+	fi
 }
 
-# Install GNOME Apps
-function gnome-apps {
-    if (eval `resize` && whiptail --title \
-        "GNOME Apps"  --yesno \
-        "Current list of GNOME apps: \n\n$(cat $GNOMEAPPS) \n\nWould you like to install the GNOME core app suite?" \
-        $LINES $COLUMNS $(( $LINES - 12 )) \
-        --scrolltext ) then
-        show_info 'Installing '$NAME'...'
-        show_warning 'Requires root privileges'
-        # Feel free to change the contents of 'gnome-apps.list' in the data folder to whatever suits your preference.
-        sudo apt-get install -y --no-install-recommends $(cat $GNOMEAPPS)
-        # Done
-        show_success 'Done.'
-        # Check
-        EXITSTATUS=$1
-        if [[ $EXITSTATUS != 0 ]]; then
-            whiptail --title "Finished" --msgbox "GNOME apps are installed." 8 78
-            gnome
-        else
-            whiptail --title "Finished" --msgbox "GNOME apps installation complete." 8 78
-            gnome
-        fi
-    else
-        gnome
-    fi
+# Install GNOME Core Apps
+function install_gnome_apps {
+	display_title "Starting 'install_gnome_apps' function..."
+	# Check list
+	GNOMEAPPS=$(dirname "$0")'/data/gnome-apps.list'
+	# Draw window
+	if (eval `resize` && whiptail \
+		--title "GNOME Core Apps" \
+		--yesno "Current list of GNOME core apps: \n\n$(for LINE in $(cat $GNOMEAPPS); do echo '  '$LINE; done) \n\nWould you like to install these apps?" \
+		$LINES $COLUMNS $(( $LINES - 12 )) \
+		--scrolltext ) then
+		# Install loop
+		display_info 'Installing GNOME core apps...'
+		for PACKAGE in $(cat $GNOMEAPPS); do
+			# Check if package is installed
+			check_packages $PACKAGE
+			EXITSTATUS=$?
+			# If package is not installed
+			if [ $EXITSTATUS = 1 ]; then
+				# Install package
+				display_info "'$PACKAGE' is not installed. Installing..."
+				# Admin privileges
+				elevate_privilege "apt install -y --no-install-recommends $PACKAGE"
+				# Done
+				display_success "'$PACKAGE' installation is complete."
+			else
+				# Show already installed message
+				echo "Package '$PACKAGE' is installed."
+			fi
+		done
+		# Finish
+		display_success "Installation complete."
+		whiptail --title "Finished" --msgbox "GNOME Apps are installed complete." 8 64
+		gnome
+	else
+		gnome
+	fi
+}
+
+# GNOME
+function gnome {
+	display_title "Starting 'gnome' function..."
+	# check exit status
+	EXITSTATUS=$?
+	if [ $EXITSTATUS = 0 ]; then
+		# Draw window
+		$(eval `resize` && whiptail \
+		--notags \
+		--title "Install Latest GNOME" \
+		--menu "\nWhat would you like to do?" \
+		--cancel-button "Go Back" \
+		$LINES $COLUMNS $(( $LINES - 12 )) \
+		upgrade_gnome			'Update to latest GNOME' \
+		install_gnome_desktop	'Install basic GNOME desktop' \
+		install_gnome_apps		'Install GNOME core applications' \
+		3>&1 1>&2 2>&3)
+	else
+		main
+	fi
 }
